// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj8nitEmEvs9zQZFL5NrqxBi7KtMn6FgI',
    appId: '1:570505786746:web:b5ce9541fc48b47a1352c3',
    messagingSenderId: '570505786746',
    projectId: 'attendease-cbc61',
    authDomain: 'attendease-cbc61.firebaseapp.com',
    storageBucket: 'attendease-cbc61.appspot.com',
    measurementId: 'G-TRJ4RC7ZHM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxBepk7WfA4MjhsqIb0qTLsBKIvaAb1pI',
    appId: '1:570505786746:android:85027b24f4a62bb71352c3',
    messagingSenderId: '570505786746',
    projectId: 'attendease-cbc61',
    storageBucket: 'attendease-cbc61.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3AzOGollu0dsA3xVTUwLs0FzJ6KZ1l0c',
    appId: '1:570505786746:ios:71160b84c94da1931352c3',
    messagingSenderId: '570505786746',
    projectId: 'attendease-cbc61',
    storageBucket: 'attendease-cbc61.appspot.com',
    iosBundleId: 'com.example.attendEasy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3AzOGollu0dsA3xVTUwLs0FzJ6KZ1l0c',
    appId: '1:570505786746:ios:71160b84c94da1931352c3',
    messagingSenderId: '570505786746',
    projectId: 'attendease-cbc61',
    storageBucket: 'attendease-cbc61.appspot.com',
    iosBundleId: 'com.example.attendEasy',
  );
}
